name: github-pages

on:
  push:
    tags:
      - 'v*'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
        with:
          persist-credentials: false
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
      - name: Install hatch
        run: |
          pip install hatch
      - name: Build documentation
        run: |
          hatch run docs:make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html/
        if: ${{ !env.ACT }}
